# Generated by Django 3.1.1 on 2021-07-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=200)),
                ('away', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('gameLeague', models.CharField(max_length=200)),
                ('numberTips', models.IntegerField()),
                ('ProbHome', models.IntegerField()),
                ('ProbDraw', models.IntegerField()),
                ('ProbAway', models.IntegerField()),
                ('ToWin', models.CharField(max_length=4)),
                ('lol', models.TextField()),
            ],
        ),
    ]
