# Generated by Django 3.1.1 on 2021-07-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='lol',
        ),
    ]
