# Generated by Django 3.1.1 on 2020-09-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lol',
            field=models.TextField(default='lol'),
            preserve_default=False,
        ),
    ]
