# Generated by Django 3.1.1 on 2020-09-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_lol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game',
            new_name='away',
        ),
        migrations.AddField(
            model_name='game',
            name='home',
            field=models.CharField(default='lol', max_length=200),
            preserve_default=False,
        ),
    ]
