# Generated by Django 3.1.1 on 2021-07-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_lol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='AcademiaGame',
        ),
    ]
